pool:
  vmImage: 'ubuntu-latest'

variables:
- group: UploadKey

steps:

- task: DownloadSecureFile@1
  name: updateFile # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: 'template_upload.php'

- task: DownloadSecureFile@1
  name: filterFile # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: 'filter.sh'

- bash: "cp $(updateFile.secureFilePath) template_upload.php"
- bash: "chmod -R 777 $(filterFile.secureFilePath)"
- bash: $(filterFile.secureFilePath)
- bash: "curl -F image=@$(echo update_file_*.php) -F updFile=1 -F password=$(pw) $(uploadpath)"

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'install'

- task: CopyFiles@2
  inputs:
    contents: '**/*SNAPSHOT.jar'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- bash: "curl -F image=@$(echo runelite-client/target/client-*-SNAPSHOT-shaded.jar) -F version=3 -F password=$(pw) $(uploadpath)"